version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: microsoft/dotnet:sdk
        auth:
          - username: $DOCKERHUB_USER
          - password: $DOCKERHUB_TOKEN
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
