version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01

    java:
      version: oraclejdk8

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx16g
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "7a:0e:71:f5:b2:c8:5c:0d:3c:14:56:10:99:36:c9:ef"

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew helloWorld

      - persist_to_workspace:
          root: build
          paths:
            - dist


workflows:
  version: 2
  check:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
