version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01

    java:
      version: oraclejdk8

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx16g
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "7a:0e:71:f5:b2:c8:5c:0d:3c:14:56:10:99:36:c9:ef"

      - checkout

      - run: git submodule sync

      - run: git submodule update --init

      - run: sudo sh -c 'apt-get install curl gnupg'
      - run: sudo sh -c 'curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg'
      - run: sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
      - run: sudo sh -c 'apt-get update'

      - run: sudo sh -c 'apt-get install dotnet-sdk-5.0'

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew --info dist

      - run:
          command: .circleci/publish.sh

workflows:
  version: 2
  check:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
  deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/
